### ISSUE TITLE
Compose file?

### ISSUE THREAD

**Issue by pierreozoux** [GluuFederation/gluu-docker#15]
Just stumble upon your project, and find it really nice.

I'm positively surprised by this commitment to provide Docker images. I'm just struggling to find the `docker run` line in your documentation. Until I realized that somehow, you have a python app that is doing it.

Do you plan to release some kind of `docker-compose.yml` file? Or just a `docker run` documentation would be enough for me.

Let me know if there is anything I can do to ease your work?

Thanks!

**Comment by nynymike** [comment]
This project is a component of our Docker Edition distribution, which is in beta. You can find current documentation on https://www.gluu.org/docs-docker-edition/  

Gluu Server Docker Edition is not production ready! It's just for testing right now.

Remember, the Gluu Server is many services... working together.

We use Github for tracking bugs, not support. If you have any questions, please register on https://support.gluu.org and post your questions there. 

Thanks!

**Comment by pierreozoux** [comment]
Arf, believe it or not, but I can't login to it!

I just registered a new account, and try to login with it., but nothing... (and not much browser logs to help you debug, just a 404 on a png...)

And it is not really a bug, or support, it is more a feature request. I think Docker ecosystem is nicer when we can use raw Docker also as an option, there is a big discussion about it here for instance: 
https://meta.discourse.org/t/can-discourse-ship-frequent-docker-images-that-do-not-need-to-be-bootstrapped/33205/50

And yes, I can help you also having an official docker image, it would be nice :)

**Comment by pierreozoux** [comment]
And I'm testing now, so I really don't mind testing!

**Comment by nynymike** [comment]
Did you try logging in with your email address? I see your username was invalid.

**Comment by pierreozoux** [comment]
Ok, sorry, my firefox saved my username... I opened a support also for that.

**Comment by pierreozoux** [comment]
Ok, sorry, my firefox saved my username... I opened a support also for that.
