### ISSUE TITLE
Dockerize Gluu aside Docker Edition

### ISSUE THREAD

**Issue by dalareo** [GluuFederation/gluu-docker#16]
Hi,

I've been testing Docker Edition and it is great but, is it possible to have Gluu Server CE inside a docker container? 
Docker images in this repo seem to be designed in order to be included in Docker Edition. Am I wrong? Any help?

**Comment by nynymike** [comment]
I don't think you can put CE inside a container because it doesn't run as one process. Each service needs to be dockerized.

**Comment by dalareo** [comment]
Yeah, but isn't it possible to create one container replicating chroot VM and running all the processes?

**Comment by iromli** [comment]
@dalareo 

> I can find the docker images in your repo but no information about linking them to make them work without using Docker Edition

Those images require templates that rendered before running container's entrypoint.
