### ISSUE TITLE
Swarm Horizontal Scaling

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/gluu-docker#20]
oxAuth, and maybe oxTrust, need to be swarm capable, with multiple replicas across multiple VM's to handle load.

Ideally multiple replicas on a single instance should be properly load-balanced, but the goal is to get the replicas spread horizontally across VM's to increase auth/sec through more CPU and RAM.

**Comment by iromli** [comment]
I've found that to deploy multiple oxAuth containers, we need session storage. Swarm network will load-balance request to oxAuth, hence it will raise `2018-04-01 18:05:08,218 ERROR [qtp460332449-11] [org.xdi.oxauth.auth.Authenticator] (Authenticator.java:517) - Failed to get attributes from session`. 

I'm looking at Redis cluster using docker.

**Comment by iromli** [comment]
adding Redis as cache storage fix the issue with session

**Comment by iromli** [comment]
we can use `docker service scale oxauth=2` command to scale oxAuth.

**Comment by iromli** [comment]
Closing this one because Docker Swarm Mode has the built-in command `scale`.
