### ISSUE TITLE
Change `encoded_salt` to `encode_salt`

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/gluu-docker#22]
Inside the configuration, `encoded_salt` should be named `encode_salt` to match naming conventions from standard Gluu Server CE installation.

See `/etc/gluu/conf/salt` inside CE installation:

```
encodeSalt = <salt>
```

Encoded implies that the salt is encoded, when it's really used to encode/decode information.

https://github.com/GluuFederation/docker-config-init/pull/3

**Comment by afroDC** [comment]
This would require quite a bit of refactoring on every script from the other images. Not sure if it's worth it.

**Comment by skybert** [comment]
Granted you've checked out all sources in a directory called `gluu`, it should be accomplished with something as simple as:
```bash
grep -r  encoded_salt gluu/docker-* | 
  cut -d: -f1 | 
  sort -u | 
  while read f; do 
    (cd $(dirname "${f}") && \
       sed -i 's#encoded_salt#encode_salt#g' "${f}" && \
       git commit -m "encoded_salt → encode_salt" "${f}"; 
  done
```

**Comment by iromli** [comment]
Have a look at https://github.com/GluuFederation/docker-config-init/pull/3 to see the status.
