### ISSUE TITLE
Store Gluu Configuration in /Gluu/ Directory

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/gluu-docker#26]
For ease of management in Consul, configuration entries should be stored in a `/Gluu/` directory inside Consul.

**Comment by iromli** [comment]
I propose to store them under `/gluu_config/` to address our upcoming config and secret layers (supposed to be saved in separate `/gluu_secret/`).

**Comment by afroDC** [comment]
In that regard, should we  have it under the `/Gluu/` tree, so `/Gluu/gluu_config/` and `/Gluu/gluu_secret/`?

**Comment by iromli** [comment]
How about `/Gluu/config/` and `/Gluu/secret/`?

**Comment by afroDC** [comment]
That's perfect

**Comment by iromli** [comment]
Config are stored under `/gluu/config/` directory in consul KV.
