### ISSUE TITLE
gluuhttpd: how does port 443 can be exposed without configuring?

### ISSUE THREAD

**Issue by quantonganh** [GluuFederation/gluu-docker#3]
In this file: https://github.com/GluuFederation/gluu-docker/blob/master/ubuntu/14.04/gluuhttpd/Dockerfile

I saw that you just install Apache. Where is the configuration file? No need to start it? How does port 80, 443 can be exposed to the docker host?

**Comment by nynymike** [comment]
This is handled by flask and salt.
