### ISSUE TITLE
Create shared volume for oxShibboleth and oxTrust

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-docker#30]
oxShibboleth requires metadata, config, and other files that generated by oxTrust. By utilizing shared volumes, we can distribute those files from oxTrust to oxShibboleth.

Things to consider:

- volume must be distributed to hosts where oxTrust is deployed
- volume must be distributed to hosts where oxShibboleth is deployed

Some files/directories that might be required:

- /opt/gluu/jetty/identity/conf/shibboleth3/idp/
- /opt/gluu/jetty/identity/conf/shibboleth3/sp/
- /opt/shibboleth-idp/conf
- /opt/shibboleth-idp/metadata/
- /opt/shibboleth-idp/sp/
- /opt/shibboleth-idp/temp_metadata/
- /etc/gluu/conf/

**Comment by afroDC** [comment]
https://github.com/GluuFederation/docker-oxshibboleth/commit/11b8f2e6927bea60a615b753f7ba9bdc3b671550
