### ISSUE TITLE
The command in `startServices` to gather the host IP doesn't work on Mac

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/gluu-docker#32]
```
startServices="DOMAIN=$domain HOST_IP=$(ip route get 1 | awk '{print $NF;exit}') docker-compose up -d nginx oxauth oxtrust > /dev/null 2>&1"
```
Mac doesn't have `ip route get ` and for the sake of ease of use, we need to find an alternative method to gather the host systems ip address that is platform agnostic.

**Comment by iromli** [comment]
The `run_all.sh` relies on `ip` command as well.

```
HOST_IP=$(ip route get 1 | awk '{print $NF;exit}')
```

We should change it to allow reading from env var first before auto-detecting the IP addr, something like this:

```
HOST_IP=${HOST_IP:-(ip route get 1 | awk '{print $NF;exit}')}
```
