### ISSUE TITLE
Upgrade Data Layer

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/gluu-docker#38]
The process of upgrading from old version of Gluu Server to new version of Gluu Server generally require some changes to the data layer. So simply switching the containers from 3.1.2 to 3.1.3 isn't a painless process as sometimes new schema is necessary, or additional attributes are added to certain types of entries.

These examples can all be seen [here](https://gluu.org/docs/ce/upgrade/). For 3.1.* it's mostly [schema](https://gluu.org/docs/ce/upgrade/#update-gluu-schema-files) changes, since changing oxTrust or oxAuth from 3.1.2 to 3.1.3 will handle the war file upgrades.

Going forward, we have to have a process by which customers can relatively easily upgrade the data layer to work with newer versions in the future.

**Comment by afroDC** [comment]
Here is an upgrade script that will automatically upgrade Gluu Server in place. We should take this as an example for upgrading the LDAP data for 3.1.4, as that's the only persistence layer that would impact version swaps.

https://repo.gluu.org/upd/3-1-3-sp1.sh

**Comment by iromli** [comment]
We have `gluufederation/upgrade` container to migrate data layer in DE.
