### ISSUE TITLE
3.1.4 Testing

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/gluu-docker#46]
3.1.4 will be released soon and we should do testing on the images. This is related to https://github.com/GluuFederation/gluu-docker/issues/38 as we need to figure out the upgrade flow regarding containers specifically.

**Comment by iromli** [comment]
All images for 3.1.4 are tagged as `3.1.4_dev`

**Comment by iromli** [comment]
All images for 3.1.4 are tagged as `3.1.4_01` now

**Comment by afroDC** [comment]
Okay great! Thanks @iromli
