### ISSUE TITLE
run_all.sh failes on Ubuntu 18.04 with complain about No such container: consul

### ISSUE THREAD

**Issue by kgardas** [GluuFederation/gluu-docker#49]
Hi,
I've installed fresh Ubuntu 18.04 LTS server VM. I've installed docker and docker-compose into it as provided by docker project in their repo.
Now, if I run run_all.sh either by common user who is added into the `docker` group to be able to run docker commands or by root, I still get the same result:
```
docker: Error response from daemon: No such container: consul.
```
so I would guess something is still a bit un-stable in Gluu's docker support? Or have I made any mistake on this? Thanks! Karel

**Comment by willow9886** [comment]
Best to open this on https://support.gluu.org . Thanks!

**Comment by kgardas** [comment]
This is kind of user error. `docker-compose` was downloaded but not chmoded to +x. Anyway, the script looks kind of unsafe for not checking for docker/docker-compose presence etc. So feel free to close or leave open if you plan to improve invariant checking (command presence).

**Comment by willow9886** [comment]
OK, @iromli can check and confirm. Thanks for the notes.

**Comment by afroDC** [comment]
There's no plans to add more complexity to the `run_all.sh` script as it's merely for demonstration purposes.
