### ISSUE TITLE
generate --state option is required although not ubiquitous.

### ISSUE THREAD

**Issue by kgardas** [GluuFederation/gluu-docker#50]
Hi,
living in EU country where we don't have "State" per se. So I press Enter on State question and then generation obviously failed since command line was still using `--state` but this time without supplied parameter.
When I edited `run_all.sh` and removed --state completely, generate starts to complain about
```
Error: missing option "--state".
```
would be good to allow generate to run w/o `--state` option and also to check in run_all.sh for empty state question reply.

**Comment by afroDC** [comment]
@kgardas state is common nomenclature for the initial self-signed certificate generation, so you can use the product immediately. You can use province or any other naming convention your country may use.

Also `run_all.sh` is meant for demo purposes only and may require your own customization for your deployment architecture. Please see the [technical documentation](https://gluu.org/docs/ce/3.1.3.1/docker/technical/)

**Comment by kgardas** [comment]
All right, I've probably misunderstood the purpose here. Never mind, looking into docs for customization...
