### ISSUE TITLE
Casa custom script present in 3.1.4 DE and enabled by default

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-docker#56]
@iromli, as it turns out, the cause of many issues with custom scripts (passport, u2f not working) is the present casa script enabled by default. As stated by Jose, "casa is not part of DE" and shouldn't be released yet:

<img width="1123" alt="obraz" src="https://user-images.githubusercontent.com/38302725/49190293-cf7d4380-f3c5-11e8-8df0-676792c10f72.png">

Please remove it from DE because now it constitutes a blocker for further tests.

**Comment by iromli** [comment]
noted, thanks for the report @natt-tester

**Comment by iromli** [comment]
@natt-tester does the bug occur because of the existence of the script or because it was enabled? I can disable it by default.

**Comment by willow9886** [comment]
@iromli likely because its enabled, but it shouldn't be included in our default distribution as we are going to commercially license Casa and the corresponding script.

**Comment by iromli** [comment]
@willow9886 noted, i will remove the corresponding scripts and ldifs. Thanks.

**Comment by iromli** [comment]
Casa scripts have been removed from DE distribution. Make sure to get the latest `gluufederation/config-init:3.1.4_03` and `gluufederation/opendj:3.1.4_02`

**Comment by iromli** [comment]
See screenshot below for latest changes in DE:

![no-casa](https://user-images.githubusercontent.com/231601/49557279-b8949f00-f939-11e8-8d6f-26fc987230f8.png)

Closing this issue, feel free to reopen if bug persists.
