### ISSUE TITLE
Change NGINX Ports

### ISSUE THREAD

**Issue by mikejr83** [GluuFederation/gluu-docker#58]
NOTES: Running on Docker for Windows, Linux VM in Hyper-V. Using MINGW64 shell to execute commands

After some working around a couple of issues regarding getting the single-node deployment to work I'm having trouble to getting to the UI. 

For clarity I basically had to do the following:

* Execute `run_all.sh` commands via the shell for pathing reasons in Win/MINGW
* Change the ports from 80 and 443 to 8080 and 8443 for my env
* Add the domain 'myhost.local' to my hosts file.

When I go to http://myhost.local:8080 it redirects to https://myhost.local. When I go to https://myhost.local:8443 it redirects to https://myhost.local/identity. Finally when I go to https://myhost.local:8443/identity I got a 502 bad gateway error from NGINX.

Additional configuration options passed through the `generate` command could take the http proxy's listening ports.

**Comment by afroDC** [comment]
@mikejr83 can you make an issue on [support.gluu.org](support.gluu.org)? We primarily use this channel "internally"

**Comment by mikejr83** [comment]
Yep. Can do. Sorry about that!

MG

**Comment by afroDC** [comment]
No problem! Closing this now.
