### ISSUE TITLE
Gluu Server 3.1.5 Images

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/gluu-docker#59]
Gluu Server 3.1.5 is close to being released. We will need to do some building around the new changes. The most time consuming process will be ensuring the configuration generation matches CE.

**Comment by lrabiet** [comment]
Hi,
Is the code https://github.com/GluuFederation/gluu-docker/tree/3.1.5/examples/single-host close to the final one ? Will the version 3.1.5 of single host be with google kms ? 3.1.4 is not that's why I am asking.

**Comment by iromli** [comment]
Done.
