### ISSUE TITLE
can't make it work on eks

### ISSUE THREAD

**Issue by aparraga** [GluuFederation/gluu-docker#63]
Hi,

I'm trying to install the gluu on Amazon EKS service, which is the one we're using right now.
Not sure what's the missing piece, I have followed step by step from the Minikube tutorial, except the nginx part, that I have use the one at google cloud tutorial to ensure that an ALB is created.
After that, instead of using the Minikube IP, I have executed the following command 
```
[~/]$kubectl get svc -n ingress-nginx
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP        PORT(S)                      AGE
default-http-backend   ClusterIP      172.XX.XX.XX   <none>             80/TCP                       91d
ingress-nginx          LoadBalancer   172.XX.XX.XX    a93ab66983871...   80:30606/TCP,443:31496/TCP   13h
```
and resolve the EXTERNAL-IP of the ingress-nginx to execute the commands from the Minikube, but instead of using the ```minikube ip```, use the external IP resolved from the previous command,

So, for example, if the external IP resolves to 24.251.22.208, use:
```
NGINX_IP=24.251.22.208  sh deploy-pod.sh
```

But I think I miss something, because after completing the installation, the ALB does not redirect to any instance because all are Out of Service.
If I execute a curl against the port 31179, which is the one the ALB pings to the instances heartbeat, I get:

```
[ec2-user@ip-xx-xx-xx-xxx ~]$ wget http://localhost:31179/hea
--2019-02-25 08:02:01--  http://localhost:31179/hea
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:31179... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2019-02-25 08:02:01 ERROR 503: Service Unavailable.
```

Is anything else that I should take into account to make the gluu work on EKS?

Thank you in advance

**Comment by willow9886** [comment]
Hi @aparraga we are not offering community support on this project. In fact, we're in the process of updating the license for DE to the Gluu Support License, which means you need an active Gluu subscription to use.  

If you need a FOSS deployment, please stick to the standard VM deployment, as documented [here](https://www.gluu.org/docs/ce/installation-guide/install/).
