### ISSUE TITLE
Output all container logs into a seperate enviornemnt to access at all times

### ISSUE THREAD

**Issue by mogluu** [GluuFederation/gluu-docker#64]
We need to have this feature added . Logs from all our containers need to be synced into a separate container in case of any crashes .
Example :
https://kubernetes.io/docs/concepts/cluster-administration/logging/#USING-A-SIDECAR-CONTAINER-WITH-THE-LOGGING-AGENT

https://github.com/kiyoto/docker-fluentd

https://github.com/gocardless/logjam

https://github.com/gliderlabs/logspout

**Comment by iromli** [comment]
This is not a built-in feature of DE. Instead we provide docs (and gist) on how to use existing 3rd-party logging management tools, i.e. ELK (Elastic, Logstash, Kibana). The docs are in unreleased DE 3.1.5 repo.
