### ISSUE TITLE
Make license more permissive

### ISSUE THREAD

**Issue by heidemn** [GluuFederation/gluu-docker#69]
Why is e.g. "oxauth" licensed under the MIT license, but "gluu-docker", "oxauth-docker" etc. require 

> "an active support subscription for this software with either Gluu or one of Gluu's OEM partners after using the software for more than 30 days"?

Of course I understand that Gluu wants to earn some money. But nowadays, container-based deployment is how most people want to run their software.

Will the license be made more permissive when moving Gluu DE from Beta to GA?

Is it allowed to build own Docker images based on the MIT-licensed components, not using the software under this special license?

**Comment by willow9886** [comment]
Docker deployments are quite difficult to support. 

You're free to build your own assets and recipe, but we won't provide support, and it's taken us years to build our strategy.
