### ISSUE TITLE
Ubuntu gluucas Dockerfile typo

### ISSUE THREAD

**Issue by SerialVelocity** [GluuFederation/gluu-docker#7]
Hey,

I think there's a typo in the gluucas Dockerfile. It references ```ASIMBA_DOWNLOAD_URL``` but I think it should reference ```CAS_DOWNLOAD_URL```.

Best,
SerialVelocity

**Comment by mzico** [comment]
Thanks, @SerialVelocity! Assigning to Gluu Engineer.

**Comment by iromli** [comment]
Fixed in e3714ac3a6beb75fbd017737d789b87b838759c9. 
Thanks for the report.
