### ISSUE TITLE
What happened to docker-openldap?

### ISSUE THREAD

**Issue by skybert** [GluuFederation/gluu-docker#70]
With Gluu 3.x, OpenLDAP replaced OpenDJ as the default LDAP backend: https://www.gluu.org/press-releases/2017/gluu-server-3-0-includes-support-for-the-latest-shibboleth-idp-and-openldap/, but I see the docker compose in this repo was changed back to OpenDJ in 00b9beaa4c1c18bd813971420839dd6f8a877d88.

I don't know if this change was related, but the `docker-openldap` Docker image is no longer downloadable:

```
Pulling ldap (gluufederation/openldap:3.1.3_03)...
pull access denied for gluufederation/openldap, repository does not exist or may require 'docker login'
```

And the git repo is gone as well:
```
❯ git clone https://github.com/GluuFederation/docker-openldap.git
Cloning into 'docker-openldap'...
Username for 'https://github.com': 
Password for 'https://github.com': 
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/GluuFederation/docker-openldap.git/'
```

What happend to `docker-openldap`?

**Comment by willow9886** [comment]
Hi @skybert , we decided to remove OpenLDAP. We couldn't get replication working as expected in a stable way. We are officially deprecating OpenLDAP from Gluu Server CE 4.0, and have decided to pull support from DE completely.  

Thanks,  
Will
