### ISSUE TITLE
SchemaError creating resources (kubectl apply -f)

### ISSUE THREAD

**Issue by miguelramosfdz** [GluuFederation/gluu-docker#77]
$ kubectl apply -f config-roles.yaml

Current Behavior
Failes with the following output
error: SchemaError(io.k8s.api.autoscaling.v2beta1.ExternalMetricSource): invalid object doesn't have additional properties

retrying with --validate=false solves the problem

**Comment by mogluu** [comment]
This is not an issue with Gluu. Please make sure your versions of k8 matches and are up to date. Docker or minikube might have installed a kubectl that does not meet the same version kubectl installed by you. Please try to reinstall the **latest version of kubectl.
