### ISSUE TITLE
No release or changelogs for DE upgrades

### ISSUE THREAD

**Issue by MdStart** [GluuFederation/gluu-docker#85]
Don't see any updates or readme for DE version upgrades like now DE is 3.1.6  but what major improvement or feature or bugs fixed no info from older version isn't clear. 
Also does the gluu CE changes/fexes gets added to the DE edition also or it is separately being developed?

**Comment by iromli** [comment]
Hi @MdStart 

> Don't see any updates or readme for DE version upgrades like now DE is 3.1.6 but what major improvement or feature or bugs fixed no info from older version isn't clear.

In the upcoming release we will have aggregated changelog for all components.

> Also does the gluu CE changes/fexes gets added to the DE edition also or it is separately being developed?

We synchronized the patches/features from upstream CE to DE, although not all features are applicable in DE or they are require more work in DE.
