### ISSUE TITLE
Password not geting validated with regex pattern in enable custom validation api - /identity/attribute/update/ gluu docker edition 3.1.4

### ISSUE THREAD

**Issue by MdStart** [GluuFederation/gluu-docker#86]
I was trying to add custom validation in gluu 3.1.4 docker edition from /identity/attribute/update for password field.

I added ^(?=.[a-z])(?=.[A-Z])(?=.\d)(?=.[@$!%#?&])[A-Za-z\d@$!#%?&]{8,20}$ in regex pattern and checked the enable custom validation for this attribute option.

But after this changes when I tried to update password or add people from Users section or password for exisitng user it's not validating the the regex.

Let me know if you need more info.

**Comment by iromli** [comment]
Hi @MdStart this issue seems related to oxTrust.
Please open ticket at support.gluu.org.

Thanks for reporting.
