### ISSUE TITLE
why are you requiring to obtain Google Cloud Platform KMS credentials?

### ISSUE THREAD

**Issue by encryptblockr** [GluuFederation/gluu-docker#90]
Why can't we run and test gluu using docker locally without having to have an account with a cloud provider?

What if i want to run this on internal server and self host? why is required step to have Google Cloud Platform to create KMS file???

```
#3. Obtain Google Cloud Platform KMS credentials JSON file, save it as gcp_kms_creds.json.
```

**Comment by mogluu** [comment]
You do not need a google cloud platform credential to run Gluu docker. Its used to auto unseal the vault when one wants to use it for long term. https://gluu.org/docs/ce/installation-guide/install-docker/#set-up-vault-auto-unseal

But you can always just manually unseal it. Check test-drive https://gluu.org/docs/ce/installation-guide/test-drive/.
