### ISSUE TITLE
how to run gluu by docker? I need a docker-compose sample

### ISSUE THREAD

**Issue by FatemeGhasemi** [GluuFederation/gluu-docker#92]
I clone this project and do every thing that written in documentation step by step ,but get this warning and process get in to the loop:

```
WARNING - 2020-01-07 11:50:22,338 - Config backend is not ready; reason=config 'hostname' is not available; retrying in 5 seconds.
```

**Comment by nynymike** [comment]
You'll need to register on https://support.gluu.org and post your question there. We use Github issues only to address verified bugs or vetted enhancements.
