### ISSUE TITLE
oxpassport pod loosing the configuration after restart

### ISSUE THREAD

**Issue by mookkiah** [GluuFederation/gluu-docker#93]
To [configure](https://gluu.org/docs/ce/3.1.4/authn-guide/inbound-saml-passport/#register-external-idps-with-home-idp) passport, we have to update /etc/gluu/conf directory files. In Kubernetes [deployment](https://github.com/GluuFederation/gluu-docker/blob/3.1.6/examples/kubernetes/aws/oxpassport/oxpassport.yaml) there is no persistent volume or volume from cofigmap used for this directory. Due to this, when pod restarts configuration is getting deleted.

**Comment by moabu** [comment]
Kubernetes has been moved to [EE](https://github.com/GluuFederation/enterprise-edition) and this issue is not present. As for docker compose please find the latest [here](https://github.com/GluuFederation/community-edition-containers)
